# Generated by Django 2.1.1 on 2018-09-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('name', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1024)),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='news',
            unique_together={('category', 'date', 'name')},
        ),
    ]
